spring.application.name=TransactionService
# Puerto del Transaction Service
server.port=2040

# Base de datos propia del Transaction Service
spring.datasource.url=jdbc:mysql://localhost:3306/transaction_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# validate = JPA verifica que las tablas existan pero NO las crea
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT ? misma clave que Auth Service
jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo

# URL del User Service ? para verificar que el usuario existe
userservice.url=http://localhost:8082

# Configuración de Logging profesional
logging.level.root=INFO
logging.level.com.example.TransactionService=DEBUG

# Archivo de salida centralizado de SMCFT
logging.file.name=logs/transaction-service.log