spring.application.name=UserService
# Puerto del microservicio
server.port=2031

# Conexi�n a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/user_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo
# Niveles de log

logging.level.com.example.UserService=DEBUG
logging.level.root=INFO

# Archivo de logs para este servicio
logging.file.name=logs/user-service.log