spring.application.name=VehicleService
# Puerto del Vehicle Service
server.port=2032

# Base de datos propia del Vehicle Service
# Separada de los dem�s microservicios ? cada uno tiene su propia BD
spring.datasource.url=jdbc:mysql://localhost:3306/vehicles_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# validate = JPA verifica que las tablas existan pero NO las crea
# Flyway es quien crea las tablas con los scripts SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway ejecuta autom�ticamente los scripts de db/migration al iniciar
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# URL del User Service para verificar que el propietario existe
userservice.url=http://localhost:2031

jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo

# Configuraci�n de Logging
logging.level.root=INFO
logging.level.com.example.VehicleService=DEBUG

# Archivo de salida unificado para SMCFT
logging.file.name=logs/vehicle-service.log

springdoc.api-docs.path=/api/v1/vehicles/v3/api-docs