spring.application.name=gateway
server.port=2020

# El Gateway no necesita base de datos propia ni Flyway
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false

# Clave secreta global para validar tokens antes de retransmitir las peticiones
jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo

# Niveles de Log para monitorear el enrutamiento en tiempo real
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.file.name=logs/gateway-service.log

# ===================================================================
# CONFIGURACIÓN DE SWAGGER / OPENAPI CENTRALIZADO - LOS 12 SERVICIOS
# ===================================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.enable-native-support=true

# 1. Auth Service (Puerto: 2022)
springdoc.swagger-ui.urls[0].name=01. Autenticacion y Control de Sesiones (Auth)
springdoc.swagger-ui.urls[0].url=/api/v1/auth/v3/api-docs

# 2. User Service (Puerto: 2031)
springdoc.swagger-ui.urls[1].name=02. Gestion de Operadores e Identidades (Users)
springdoc.swagger-ui.urls[1].url=/api/v1/users/v3/api-docs

# 3. Vehicle Service (Puerto: 2032)
springdoc.swagger-ui.urls[2].name=03. Parque Vehicular y Patentes (Vehicles)
springdoc.swagger-ui.urls[2].url=/api/v1/vehicles/v3/api-docs

# 4. Border Crossing Service (Puerto: 2023)
springdoc.swagger-ui.urls[3].name=04. Controles de Transito y Equipajes (Border Crossings)
springdoc.swagger-ui.urls[3].url=/api/v1/border-crossings/v3/api-docs

# 5. Entry Service (Puerto: 2025)
springdoc.swagger-ui.urls[4].name=05. Declaraciones y Registros de Ingreso (Entries)
springdoc.swagger-ui.urls[4].url=/api/v1/entries/v3/api-docs

# 6. Sanitary Service (Puerto: 2029)
springdoc.swagger-ui.urls[5].name=06. Inspecciones y Visados Sanitarios (Sanitary)
springdoc.swagger-ui.urls[5].url=/api/v1/sanitary/v3/api-docs

# 7. Deadline Service (Puerto: 2024)
springdoc.swagger-ui.urls[6].name=07. Control de Alertas y Tiempos Limite (Deadlines)
springdoc.swagger-ui.urls[6].url=/api/v1/deadline-alerts/v3/api-docs

# 8. Item Category Service (Puerto: 2026)
springdoc.swagger-ui.urls[7].name=08. Catalogo de Categorias Arancelarias (Items)
springdoc.swagger-ui.urls[7].url=/api/v1/item-categories/v3/api-docs

# 9. Transaction Service (Puerto: 2040)
springdoc.swagger-ui.urls[8].name=09. Conciliacion y Pagos Aduaneros (Transactions)
springdoc.swagger-ui.urls[8].url=/api/v1/transactions/v3/api-docs

# 10. Report Service (Puerto: 2028)
springdoc.swagger-ui.urls[9].name=10. Motor de Reporteria Estadistica (Reports)
springdoc.swagger-ui.urls[9].url=/api/v1/reports/v3/api-docs

# 11. Notification Service (Puerto: 2027)
springdoc.swagger-ui.urls[10].name=11. Mensajeria y Despacho de Alertas (Notifications)
springdoc.swagger-ui.urls[10].url=/api/v1/notifications/v3/api-docs

# 12. Audit Service (Puerto: 2021)
springdoc.swagger-ui.urls[11].name=12. Bitacora e Historial Forense (Audits)
springdoc.swagger-ui.urls[11].url=/api/v1/audits/v3/api-docs