spring.application.name=gateway
server.port=2020

# El Gateway no necesita base de datos propia ni Flyway
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=false

# Clave secreta global para validar tokens antes de retransmitir las peticiones
jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo

# Niveles de Log para monitorear el enrutamiento en tiempo real
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.file.name=logs/gateway-service.log

# Swagger/OpenAPI configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true