spring.application.name=ReportService
# Puerto del Report Service
server.port=2028

# Base de datos propia del Report Service
spring.datasource.url=jdbc:mysql://localhost:3306/report_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# validate = JPA verifica que las tablas existan pero NO las crea
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT ? misma clave que Auth Service
jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo

# URL del Border Crossing Service
bordercrossingservice.url=http://localhost:8084

# Configuración de Logging
logging.level.root=INFO
logging.level.com.example.ReportService=DEBUG

# Archivo de salida unificado
logging.file.name=logs/report-service.log