spring.application.name=BorderCrossingService
# Puerto del Border Crossing Service
server.port=8084

# Base de datos propia
spring.datasource.url=jdbc:mysql://localhost:3306/border_crossing_db

spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# validate = JPA verifica que las tablas existan pero NO las crea
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway ejecuta los scripts automáticamente al iniciar
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# URL del Vehicle Service ? para verificar y actualizar estado del vehículo
vehicleservice.url=http://localhost:8083

# URL del Item Category Service ? para validar categorías de equipaje
itemcategoryservice.url=http://localhost:8088
