spring.application.name=SanitaryService
# Puerto del Sanitary Service
server.port=2029

# Base de datos propia del Sanitary Service
# Se le agregan los parametros de escape para asegurar la conexion con Java 21
spring.datasource.url=jdbc:mysql://localhost:3306/sanitary_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# validate = JPA verifica que las tablas existan pero NO las crea
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT ? misma clave que Auth Service
jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo

# URLs de comunicacion interservicio ACTUALIZADAS a tus puertos reales
vehicleservice.url=http://localhost:2032
userservice.url=http://localhost:2031

# Configuraci�n de Niveles de Logging
logging.level.root=INFO
logging.level.com.example.SanitaryService=DEBUG

# Ruta del archivo de salida unificado
logging.file.name=logs/sanitary-service.log

springdoc.api-docs.path=/api/v1/sanitary/v3/api-docs