# Puerto del Auth Service
# Cada microservicio debe tener un puerto diferente para no chocar
server.port=8081

# Base de datos propia del Auth Service
# Separada de smcft_users porque cada microservicio tiene su propia BD
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# validate = JPA verifica que las tablas existan pero NO las crea
# Flyway es quien crea las tablas mediante los scripts SQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway ejecuta automáticamente los scripts de db/migration al iniciar
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Clave secreta para firmar los tokens JWT
# En producción debe ir en variables de entorno, nunca hardcodeado
jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo

# Tiempo de vida del token: 86400000 ms = 24 horas
jwt.expiration=86400000

# URL del User Service para comunicación entre microservicios
# Auth Service consulta a User Service durante el login
userservice.url=http://localhost:8082

# Nombre identificador del microservicio
spring.application.name=AuthService