server.port=8760
spring.application.name=eureka-server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://localhost:8760/eureka
eureka.instance.preferIpAddress=true
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
logging.level.root=INFO
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG
