spring.application.name=ItemCategoryService
# Puerto del Item Category Service
server.port=8088

# Base de datos propia del Item Category Service
spring.datasource.url=jdbc:mysql://localhost:3306/item_category_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# validate = JPA verifica que las tablas existan pero NO las crea
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway ejecuta los scripts automáticamente al iniciar
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=smcft_clave_super_secreta_2025_sistema_fronterizo